### ISSUE TITLE
'set' command irregularities

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#28] opened 2017-06-10 04:49 UTC
This issue is a catch-all for any issues with 'set'

set <player> <initdice|initroll> <value> does nothing. (act.wizard.cpp:3655-3664).

set <player> <hunger|thirst> <value> removes from 'score' output but doesn't gag hunger/thirst messages.  ~~Output in 'score' does not seem to return.~~

Setting a player's level to 0 removes them from wholist. Intended behavior?

nowizlist doesn't seem to be implemented (act.wizard.cpp:3770, commented out). I wonder why.

idnum doesn't seem to to anything and would probably screw up the DB if it did. Remove it?

passwd doesn't seem to to anything. Bugged?

newbie seems bugged. PLR: output from stat doesn't get updated properly.

pg does not seem implemented (missing case in act.wizard.cpp). Remove it?

**Comment by luciensadi** [comment] 2017-06-10 14:37
initdice/initroll doing nothing are because it calls affect_total() immediately afterwards, which wipes those values and re-calculates them. To make that feature work, I'd have to somehow make the set command apply a permanent affect to their init dice/roll that was included in affect_total(). I'm thinking I'll just disable initdice/initroll instead due to the hackiness of that fix and the limited range of times we'd actually want to set that value for a character.

Hunger/thirst/etc looks like it should work.

Level 1 is for normal players / mortals. I have no idea what the effect of setting their level to 0 would be unless the goal is to make them sub-human. Changed minimum to 1.

nowizlist is not referenced anywhere in the code, so I imagine it's commented out because it doesn't do anything.

idnum can only be performed by the first player (president by default) and can only be done on NPCs. I don't know what it's for, but I'm inclined to leave it until it proves to be a problem.

passwd sets the password properly but wasn't saving to DB. This should hopefully be fixed with the new save logic.

newbie is set properly, but affect_total removes it, which is the expected behavior.

I don't know what PG was used for before, but I'm yoinking it for playergroups now.

**Comment by jalles76** [comment] 2017-06-10 15:04
Agree on initdice/initroll and rest.

**Closed** 2017-06-10 15:07 UTC
Labels: bug
